name: m3e_utils_lib
description: "A new Flutter package project."
version: 0.0.1
homepage: https://fredgrott.substack.com

environment:
  sdk: ^3.10.0-162.1.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  motor: ^1.0.1
  material_symbols_icons: ^4.2874.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
